# --------------
# -- Settings --
# --------------

title: Sayf Eddin Ahmed
description: >-
  Pursuing my goals to give to society through technology.
baseurl: ""
url: "https://sayf-eddin.me/"

# Compressed with TinyPNG
images:
  favicon: "/images/favicon.ico"
  hero: "/images/profile.jpg"
  seo: "/images/seo.png"
  education: "/images/syracuse.png"

about:
  - >
      My personal mission is to give to society through technology. 
      I am always eager to learn and often become obsessed with accomplishing tasks — the more 
      difficult the better. Within my various endeavors, I spend my time working on projects alone 
      and closely collaborating. I am constantly looking for ways to improve myself and help 
      those&nbsp;around&nbsp;me.
  - >
      I love exercising my creativity by playing guitar or painting, especially with 
      friends. I also enjoy going outside to play soccer or for a long hike.
      My most recent achievement is climbing Mont&nbsp;Blanc.

featured:
  - title: "Centro Bus Schedule GTFS API"
    images: 
      - "/images/api_doc.png"
      - "/images/SU443_routes.png"
      - "/images/bus_api.png"
    text: >
      REST API built in Django for Syracuse University’s Centro [bus&nbsp;schedules](https://www.centro.org/colleges/syracuse-university){:target="_blank"}
      
      * Scripts to pull and read [GTFS data](https://transitfeeds.com/p/central-new-york-rta/524){:target="_blank"} and populate a PostgreSQL database with tables for services, routes, trips, and&nbsp;stops
      
      * Endpoints with query parameter filters for all tables and the South Campus bus schedule for&nbsp;today

      * Deployable in Docker container with images for PostgreSQL, MinIO, and&nbsp;Redis
    
  - title: "Dow Jones Marketing"
    images: 
      - "/images/wsj_pro.png"
      - "/images/journal_house.png"
      - "/images/wsj_store.png"
      - "/images/wsj_email.png"
    text: >
      Web assets for The Wall Street Journal, MarketWatch, and Barron’s

      * Multi-layered websites such as [wsjpro.com](https://www.wsjpro.com){:target="_blank"} and [journalhouse.com](https://journalhouse.com/){:target="_blank"}
      
      * Shop pages for news subscriptions and bundles sales typically hosted at [store.wsj.com](https://store.wsj.com){:target="_blank"}

      * Hundreds of emails for commerce, customer engagement, commercial partnerships, and WSJ&nbsp;events
      

work:
  - company: "Hogarth Worldwide"
    role: "Front-End Developer"
    years: "2021-2022"
    description: >
      * Perfomed as a web developer on Dow Jones products including The Wall Street Journal, MarketWatch, and&nbsp;Barron’s

      * Collaborated with copywriters, designers, and marketing managers on nearly 300 time-sensitive campaigns with multiple&nbsp;assets

      * Engineered eye-catching emails, developed customer-facing shop pages with JavaScript and Webpack, co&#8209;managed 
      [wsjpro.com](https://www.wsjpro.com){:target="_blank"} through WordPress, and innovated an entire web platform for WSJ Journal House on Splash’s event content management system (CMS)


  - company: "Syracuse University Division of Marketing and Communications"
    role: "Full-Stack Developer Intern"
    years: "2020-2021"
    description: >
      * Implemented and managed pythonic applications and services for Syracuse University’s 15,000 WordPress&nbsp;sites

      * Contributed on a team of developers on full-stack agile development, systems administration, and data&nbsp;analysis

      * Programmed applications using Django, pandas, Django REST framework, Ansible Tower API, Docker, Go, Fastly, and&nbsp;Wagtail

      * [Read more at syracuse.edu](https://www.syracuse.edu/stories/student-interns-marketing/#s:sayf-ahmed-web-development-and-teamwork){:target="_blank"}


  - company: "Syracuse University School of Information Studies"
    role: "Junior Django Developer"
    years: "2019-2020"
    description: >
      * Designed and improved complex web apps in Django for the School of Information Studies of Syracuse&nbsp;University

      * Utilized test driven development, accessibility, and Kanban development with PostgreSQL and&nbsp;CI/CD


education: >
  <b>Bachelor of Science in Computer&nbsp;Science</b><br>
  Minor in Cognitive&nbsp;Science<br>
  May 2021<br>

footer:
  - name: "GitHub"
    link: "https://github.com/sayf-eddin"

  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/sayf-ahmed/"

  - name: "Resume"
    link: "/assets/Sayf Ahmed Resume.pdf"

  - name: "HackerRank"
    link: "https://www.hackerrank.com/sayf_eddin_ahmed"

# Build settings
theme: minima

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
