# --------------
# -- Settings --
# --------------

title: Sayf Eddin Ahmed
email: sayf.eddin.ahmed@gmail.com
description: >-
  Pursuing my goals to give to society through technology.
baseurl: ""
url: "https://sayf-eddin.me/"

# Compressed with TinyPNG
images:
  favicon: "/images/favicon.png"
  hero: "/images/profile.jpg"
  seo: "/images/seo.png"

about:
  - text: >
      My personal mission is to give to society through my passion for innovation and technology. 
      I am always eager to learn, and I often get obsessed with accomplishing tasks — the more 
      difficult the better. The time I have spent heavily working on projects alone does not mean 
      I spend any less closely collaborating with stakeholders. I am constantly looking for ways to
      improve myself and help those around me.
  - text: >
      I love exercising my creativity by playing music with my guitar or painting, especially with 
      friends. I also enjoy being active through outdoor activities from hiking to soccer.

featured:
  - image: "/images/bus_api.png"
    title: "Centro Bus Schedule API"
    text: >
      REST API built in Django


# Build settings
theme: minima

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
