# --------------
# -- Settings --
# --------------

title: Sayf Eddin Ahmed
description: >-
  Pursuing my goals to give to society through technology.
baseurl: ""
url: "https://sayf-eddin.me/"

# Compressed with TinyPNG
images:
  favicon: "/images/favicon.png"
  hero: "/images/profile.jpg"
  seo: "/images/seo.png"
  education: "/images/syracuse.png"

about:
  - >
      My personal mission is to give to society through technology. 
      I am always eager to learn, and I often get obsessed with accomplishing tasks — the more 
      difficult the better. The time I spend heavily working on projects alone does not mean 
      I spend any less closely collaborating. I am constantly looking for ways to
      improve myself and help those&nbsp;around&nbsp;me.
  - >
      I love exercising my creativity by playing guitar or painting, especially with 
      friends. I also enjoy going outside to play soccer or for a&nbsp;long&nbsp;hike.

featured:
  - title: "Centro Bus Schedule API"
    images: 
      - "/images/bus_api.png"
      - "/images/bus_api.png"
    text: >
      REST API built in Django

work:
  - company: "Hogarth Worldwide"
    role: "Front-End Developer"
    years: "2021-2022"
    description: >
      WSJ

  - company: "Syracuse University Division of Marketing and Communications"
    role: "Full-Stack Developer Intern"
    years: "2020-2021"
    description: >
      syr

  - company: "Syracuse University School of Information Studies"
    role: "Junior Django Developer"
    years: "2019-2020"
    description: >
      syr

education: >
  <b>Bachelor of Science in Computer&nbsp;Science</b><br>
  Minor in Cognitive&nbsp;Science<br>
  May 2021<br>

footer:
  - name: "GitHub"
    link: "https://github.com/sayf-eddin"

  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/sayf-ahmed/"

# Build settings
theme: minima

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
